---
name: ((deployment_name))

releases:
- name: concourse
  version: ((concourse_version))
  sha1: ((concourse_sha1))
  url: https://bosh.io/d/github.com/concourse/concourse-bosh-release?v=((concourse_version))
- name: bpm
  version: ((bpm_version))
  sha1: ((bpm_sha1))
  url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=((bpm_version))
- name: postgres
  version: ((postgres_version))
  sha1: ((postgres_sha1))
  url: https://bosh.io/d/github.com/cloudfoundry/postgres-release?v=((postgres_version))

instance_groups:
- name: web
  instances: 1
  azs: ((availability_zones))
  networks: [{name: ((network_name))}]
  stemcell: xenial
  vm_type: ((web_vm_type))
  jobs:
  - release: bpm
    name: bpm

  - release: concourse
    name: web
    properties:
      token_signing_key: ((token_signing_key))

      external_url: ((external_url))

      postgresql:
        ca_cert: ((postgres_ca))
        client_cert:
          certificate: ""
          private_key: ""
        sslmode: verify-ca
        database: &db_name atc
        role: &db_role
          name: concourse
          password: ((postgres_password))

      worker_gateway:
        host_key: ((tsa_host_key))
        authorized_keys: |
          ((worker_key.public_key))

- name: db
  instances: 1
  azs: ((availability_zones))
  networks: [{name: ((network_name))}]
  stemcell: xenial
  vm_type: ((db_vm_type))
  persistent_disk_type: ((db_persistent_disk_type))
  jobs:
  - release: postgres
    name: postgres
    provides:
      postgres-address: {as: concourse-postgres-address}
    custom_provider_definitions:
      - name: postgres-address
        type: address
    properties:
      databases:
        tls:
          private_key: ((postgres_tls.private_key))
          certificate: ((postgres_tls.certificate))
        port: 5432
        databases:
        - name: *db_name
        roles:
        - *db_role

- name: worker
  instances: 1
  azs: ((availability_zones))
  networks: [{name: ((network_name))}]
  stemcell: xenial
  vm_type: ((worker_vm_type))
  jobs:
  - release: concourse
    name: worker
    properties:
      drain_timeout: 10m
      worker_gateway: {worker_key: ((worker_key))}

variables:
- name: postgres_password
  type: password
- name: token_signing_key
  type: rsa
- name: tsa_host_key
  type: ssh
- name: worker_key
  type: ssh
- name: postgres_ca
  type: certificate
  options:
    is_ca: true
    common_name: postgresCA
- name: postgres_tls
  type: certificate
  options:
    ca: postgres_ca
    extended_key_usage:
    - server_auth
  consumes:
    alternative_name: { from: concourse-postgres-address }
    common_name: { from: concourse-postgres-address }

stemcells:
- alias: xenial
  os: ubuntu-xenial
  version: latest

update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
